version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: netology_stocks_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network

  backend:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 docker-compose-homework.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: